# name: delete packages

# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# # jobs:
# #   # This workflow contains a single job called "build"
# #   test:
# #     # The type of runner that the job will run on
# #     runs-on: ubuntu-latest
# #     # Steps represent a sequence of tasks that will be executed as part of the job
# #     steps:
# # #     - uses: actions/checkout@v2
# #       - name: Echo
# #         shell: bash
# #         run: |
# #           echo Heyyyyy
# #       - name: Clean old packages - keep last 3
# #         uses: nikhilpatil2995/container-registry@v1.0.0
# #         with:
# #           keep: 1
# #           names: ubuntu
# #       - name: Delete old packages
# #         uses: nikhilpatil2995/container-registry@main
# #         with:
# #           # Owner of the repo containing the package(s). Defaults to the owner of the repo running the action.
# #           owner: nikhilpatil2995
# #           names: ubuntu
# #           version: 2
# # #           token: ${{ secrets.token }}
# runs:
#   using: "composite"
#   steps:
#     - name: Delete old packages
#       uses: nikhilpatil2995/container-registry@main
#       with:
#       # Owner of the repo containing the package(s). Defaults to the owner of the repo running the action.
#         owner: nikhilpatil2995
#         names: ubuntu
#         version: 2
# #           token: ${{ secrets.token }}

# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}


name: Delete Package Versions

description: Deletes package versions

inputs:

#   package-version-ids:
#     description: 1,2
#     required: false

  owner:
    required: false
    default: true

#   repo:
#     description: >
#       Repo containing the package version to delete.
#       Defaults to the repo running the action.
#     required: false

  package-name: 
    name: ubuntu
  num-old-versions-to-delete:
    default: "1"

  token:
    required: false
    default: ${{ github.token }}

runs:
  using: node12
  main: dist/index.js

branding:
  icon: package
  color: blue

jobs:
  test:
    runs-on: ubuntu-latest
   steps:
      - uses: actions/delete-package-versions@v1
        with:
        owner: 'github'
        repo: 'packages'
        package-name: 'ubuntu'
        num-old-versions-to-delete: 1
        token: ${{ secrets.token }}

