name: Remove old package versions
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the package to delete'     
        required: true

jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: purge packages
        uses: nikhilpatil2995/container-registry@main
        with:
          package_name: ${{ github.event.inputs.package_name }}
          # This is a person access token with
          token: ${{ secrets.CR_PAT }}
          
# name: Delete Untagged Containers

#   # You may pin to the exact commit or the version.
#   # uses: dylanratcliffe/delete-untagged-containers@77a5033919e47c18616cb1b0a99cf50b1a034db8
#   uses: nikhilpatil2995/container-registry
#   with:
#     # The name of the package to delete
#     package_name: 
#     # Access token to use for deleting packages
#     token: 
#     # The name of the org that the containers lives under. Will default to the org of the repo that the payload trigger comes from.
#     org: # optional
#     # The name of the user that the container lives under.  Will default to the user of the repo that the payload trigger comes from.
#     user: 
