# This is a basic workflow to help you get started with Actions
name: delete packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
      - name: Clean old packages - keep last 3
        uses: nikhilpatil2995/container-registry@main
        with:
          version: 2
          names: |
            ubuntu
            container-images
      - name: Delete old packages
        uses: nikhilpatil2995/container-registry@main
        with:
          owner: ghcr.io
          names: ubuntu
          version: 2
          token: ${{ github.token }}
      - uses: actions/checkout@v2
        name: Checkout Delete Package Versions Repo
      - uses: ./
        name: Smoke Test Delete Package Versions Action
        with:
          name: 'ubuntu'
#           package-version-ids: 5e4fa09a5ace924998fa600a9f9f87ffc41464bdd95482a094f21c5c6522b557
#           num-old-versions-to-delete: 1 
          version: sha256:5e4fa09a5ace924998fa600a9f9f87ffc41464bdd95482a094f21c5c6522b557
#       - name: Clean old packages
#         uses: nikhilpatil2995/container-registry@main
#         with:
#           owner: 'nikhilpatil2995'
#           repo: 'container-registry'
#           package-name: 'ubuntu'
#           num-old-versions-to-delete: 1
#           token: ${{ github.token }}

