# This is a basic workflow to help you get started with Actions
name: delete packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@v1
      - name: Delete old images
        uses: nikhilpatil2995/container-registry@main
        with:
          image-names: ubuntu
          cut-off: 1 min ago UTC
          timestamp-to-use: created_at
          untagged-only: false
          account-type: personal
          token: ${{ secrets.token }}
  test:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
      - name: Clean old packages - keep last 3
        uses: nikhilpatil2995/container-registry@main
        with:
          version: 0
          names: |
            ubuntu
            container-images
      - name: Delete old packages
        uses: nikhilpatil2995/container-registry@main
        with:
          owner: nikhilpatil2995
          names: ubuntu
#           version: 2
          token: ${{ github.token }}
      - uses: nikhilpatil2995/container-registry@main
        name: Delete Package Versions Action
        with:
          package-name: 'ubuntu'
          owner: nikhilpatil2995
          num-old-versions-to-delete: 1 
#       - name: Clean old packages
#         uses: nikhilpatil2995/container-registry@main
#         with:
#           owner: 'nikhilpatil2995'
#           repo: 'container-registry'
#           package-name: 'ubuntu'
#           num-old-versions-to-delete: 1
#           token: ${{ github.token }}

