# This is a basic workflow to help you get started with Actions
name: delete packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
      - name: Clean old packages - keep last 3
        uses: nikhilpatil2995/container-registry@v1.0.0
        with:
          keep: 1
          names: ubuntu
      - name: Delete old packages
        uses: nikhilpatil2995/container-registry@main
        with:
          owner: nikhilpatil2995
          names: ubuntu
          version: 2
          token: ${{ github.token }}
