name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: "nikhilpatil2995"
        password: ${{ secrets.token }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/nikhilpatil2995/container-registry:latest
        docker run ghcr.io/nikhilpatil2995/container-registry:latest
        docker push ghcr.io/nikhilpatil2995/container-registry:latest
