name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: nikhilpatil2995/container-registry@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/nikhilpatil2995/hello-world:latest
        docker run ghcr.io/nikhilpatil2995/hello-world:latest
        docker push ghcr.io/nikhilpatil2995/hello-world:latest
