name: Delete old container images

on:
  schedule:
    - cron: '*/1 * * * *'  # Run it in every 5 minute
# on:
#   workflow_dispatch:
#     inputs:
#       package_name:
#         description: 'The name of the package to delete'     
#         required: true      
jobs:
  clean-ghcr:
    name: Delete old unused images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Delete old images
        uses: nikhilpatil2995/container-registry@main
        with:
          image-names: ubuntu
#           repository: nikhilpatil2995/ubuntu
#           cut-off: One month ago UTC
          cut-off: 2 seconds ago UTC+2
          timestamp-to-use: created_at
#           keep-at-least: 1
          untagged-only: false
          account-type: personal
          token: ${{ secrets.token }}
