name: Delete old container images

# on:
#   schedule:
#     - cron: '0 0 0 * *'  # the first day of the month
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the package to delete'     
        required: true      
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: nikhilpatil2995/container-registry@v1
        with:
          image-names: dev
          cut-off: One month ago UTC
          timestamp-to-use: created_at
#           keep-at-least: 1
          untagged-only: true
          account-type: personal
          token: ${{ secrets.PAT }}
